### ISSUE TITLE
Epic: Create Media App

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/StackPortfolio#225]
### Epic Description

A Media app will allow us to manage multiple images, videos, etc. for the same user. This might include videos profile images or projects.

### User Stories

- [ ] User story: Create app and set up the media model
- [ ] User story: Design and add a UI to add/manage media
- [ ] User story: Logic to delete media
- [ ] User story: Logic to resize/optimise media for upload
- [ ] User story: Logic to query correct media size for device
- [ ] User story: Enforce media restrictions per project/profile
- [ ] User story: Update project UIs to handle multiple media

Related issues (but not part of Epic directly):
#194 - Before going fully into adding a media app, it will be worth checking what moving to Amazon S3 will mean.
#178 - When users import projects, they should be able to choose from the images in their readme and import multiple images.
